import {test,expect} from '@playwright/test';
test('native menu and compact controls insert at a retained nested cursor',async({page})=>{
 await page.goto('/examples/embedded.html');await page.evaluate(()=>(window as any).example.initialize([{id:'mass',symbol:'m_B',units:'kg'}]));const h=page.locator('#first');await expect(h.locator('.me-structures button')).toHaveText(['a/b','xⁿ','xₙ','( )','√']);await expect(h.locator('.me-menus>*')).toHaveCount(3);await expect(h.locator('.me-actions button')).toHaveText(['←','→','⌫']);await h.getByRole('button',{name:'Fraction',exact:true}).click();await h.locator('.me-variables summary').click();await h.getByRole('button',{name:'Insert m_B',exact:true}).click();await expect(h.locator('.me-input')).toBeFocused();await h.locator('.me-input').press('Tab');await h.locator('.me-input').pressSequentially('2 ');expect(await page.evaluate(()=>(window as any).example.first.submit())).toBe(true);expect(await page.evaluate(()=>(window as any).example.first.getDocument().expression)).toEqual([{type:'fraction',numerator:[{type:'variable',id:'mass'}],denominator:[{type:'number',value:'2'}]}]);
});
test('suggestion strip selects first match, arrows change it and Space commits without units',async({page})=>{
 await page.goto('/examples/embedded.html');await page.evaluate(()=>(window as any).example.initialize([{id:'local',symbol:'g',units:'m/s^2'},{id:'constant',symbol:'G',units:'N*m^2/kg^2'}]));const h=page.locator('#first');await h.locator('.me-input').pressSequentially('g');await expect(h.locator('.me-suggestions [data-variable-id=local]')).toHaveAttribute('aria-selected','true');await expect(h.locator('.me-suggestions')).not.toContainText('m/s');await h.locator('.me-input').press('ArrowRight');await expect(h.locator('.me-suggestions [data-variable-id=constant]')).toHaveAttribute('aria-selected','true');await h.locator('.me-input').press('Space');expect(await page.evaluate(()=>(window as any).example.first.getDocument().expression)).toEqual([{type:'variable',id:'constant'}]);await h.locator('.me-input').press('ArrowLeft');await expect(h.locator('.me-current')).toHaveAttribute('data-path','[0]');
});
test('live API vocabulary update rerenders IDs without resetting cursor, buffer or undo history',async({page})=>{
 await page.goto('/examples/embedded.html');await page.evaluate(()=>(window as any).example.initialize([{id:'mu',symbol:'\\mu_s',aliases:['mu']} ]));const h=page.locator('#first');await h.locator('.me-input').pressSequentially('mu 2');const path=await h.locator('.me-current').getAttribute('data-path');await page.evaluate(()=>(window as any).example.first.updateVocabulary([{id:'mu',symbol:'\\mu_k',aliases:['mu'],units:'1'}]));await expect(h.locator('.me-current')).toHaveAttribute('data-path',path!);await expect(h.locator('.me-field annotation')).toContainText('\\mu_k');expect(await page.evaluate(()=>(window as any).example.first.getDocument().pending.text)).toBe('2');await h.locator('.me-input').press('Control+z');expect(await page.evaluate(()=>(window as any).example.first.getDocument().expression)).toEqual([{type:'variable',id:'mu'}]);await h.locator('.me-variables summary').click();await expect(h.getByRole('button',{name:'Insert \\mu_k',exact:true})).toBeVisible();
});
